"""New Migration

Revision ID: 90af143c051c
Revises: 53498a699f62
Create Date: 2023-05-24 09:42:35.673574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90af143c051c'
down_revision = '53498a699f62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
