"""User refactor

Revision ID: af5e936094c1
Revises: 90af143c051c
Create Date: 2023-05-24 16:47:23.310726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5e936094c1'
down_revision = '90af143c051c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'net_worth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('net_worth', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
